apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: loggkamel-proxy
  namespace: sikkerhetstjenesten
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  schedule: "0 5 * * 1-5" # Runs 5am UTC weekdays (7am Oslo time summer and 6am Oslo time winter)
  resources:
    limits:
      memory: 5Gi
    requests:
      cpu: 200m
      memory: 4Gi
  backoffLimit: 1
  webproxy: true
  filesFrom:
    - secret: db2-license
      mountPath: /app/lib