management:
  info:
    git:
      mode: simple
  observations:
    annotations:
      enabled: true
  health:
    ssl:
      enabled: false
    ping:
      enabled: false
    diskspace:
      enabled: false
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: health,info,prometheus

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: loggkamel-proxy
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jpa:
    database-platform: org.hibernate.dialect.DB2Dialect
    hibernate:
        ddl-auto: validate
    show-sql: false

springdoc:
  swagger-ui:
    oauth:
      client-id: ${azure.app.client.id}
    csrf:
      enabled: true