spring:
  datasource:
    #TODO: populate username and password with secrets at runtime
    url: jdbc:db2://localhost:50000/path-to-db-goes-here #TODO: fill this in with prod db connection info
    username: db2admin
    password: db2admin