name: Build and deploy main
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  test-build-deploy:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    permissions:
      actions: read
      contents: write
      security-events: write
      id-token: write
    uses: ./.github/workflows/build-and-push.yml
  deploy:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: test-build-deploy
    strategy:
      matrix:
        cluster: [ dev-gcp ]
    name: Deploy to ${{ matrix.cluster }}
    environment: ${{ matrix.cluster }}:sikkerhetstjenesten
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@7c152a10f4da3ca352d57a25eba0b3a8e04882f9 # Deploy
        env:
          PRINT_PAYLOAD: true
          RESOURCE: .nais/naiserator.yaml
          CLUSTER: ${{ matrix.cluster }}
          VARS: .nais/${{matrix.cluster}}.json
          IMAGE: ${{ needs.test-build-deploy.outputs.image }}